baseURL = 'https://loginovsky.com/'
languageCode = 'en-us'
title = "Michael Loginovsky"
theme = "m10c"
publishDir = 'docs'
#themesDir = "../.."
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/posts/cv/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/posts/projects/"
    weight = 3

[params]
  author = "Michael Loginovsky"
  description = "Cloud engineering, IaC automation, DevSecOps with Kubernetes"
  menu_item_separator = " | "
  favicon = "/favicon.png"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/cloud-simple"
  [[params.social]]
    icon = "linkedin"
    name = "linkedIn"
    url = "https://www.linkedin.com/in/mloginovsky"

  # My theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#6fa8dcff"
