baseURL = 'https://loginovsky.com/'
languageCode = 'en-us'
title = "Michael Loginovsky"
theme = "m10c"
publishDir = 'docs'
#themesDir = "../.."
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    # Graduated as a System Engineer
    # Have been working in IT sphere for 20+ years
    # Participated in dozens projects as system/network administrator, system developer, system architect
    # As a **Head of Infrastructure** participated in building an MMOG application with 1M+ simultaneous players
    # Switched to **The Cloud** and became adherent of **cloud native** foundation:
        # AWS - the author of the introductory tutorial on how to [Quickly switch to AWS for System Administrators](link to gitlab.com/cloud-simply/ce)
        # IaC - [Terraform Associate](link to Certificate) cerified
        # Kubernetes - [CKA](link to Certificate), [CKAD](link to Certificate) cerified (CKS is in progress)
	# GoLang - have got slight experience with pet projects](https://gist.github.com/mtilson)
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/posts/cv/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/posts/projects/"
    weight = 3
    # Active projects
        # World Chess DevOps and Cloud Engineer (reference to worldchess.com)
        # tilson-biz (reference to tilson.biz)
        # Cloud Engineering Cirriculum (reference to github.com/cloud-simply/ce)

[params]
  author = "Michael Loginovsky"
  description = "Cloud engineer, IaC automation adherent, delighted with Kubernetes"
  menu_item_separator = " | "
  favicon = "/favicon.png"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/cloud-simple"
  [[params.social]]
    icon = "linkedin"
    name = "linkedIn"
    url = "https://www.linkedin.com/in/mloginovsky"

  # My theme
  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#6fa8dcff"
